[package]
name = "nostr-tool"
version = "0.1.0"
edition = "2021"
description = "A CLI tool to interact with nostr"
authors = ["0xtr <oxtrr@protonmail.com>"]
readme = "README.md"
homepage = "https://github.com/0xtrr/nostr-tool"
repository = "https://github.com/0xtrr/nostr-tool"
license = "MIT"
keywords = ["nostr", "tool"]
categories = ["command-line-utilities"]

[dependencies]
chrono = { version = "0.4.22", features = ["serde"] }
clap = { version = "4.0.22", features = ["derive"] }
serde = { version = "1.0.147", features = ["derive"] }
tungstenite = "0.17.3"
secp256k1 = { version = "0.25", features = ["bitcoin_hashes", "global-context", "rand-std"] }
serde_json = "1.0.87"
nostr_rust = "0.16.0"
csv = "1.1.6"
